### ISSUE TITLE
App doesn't work in Firefox [MacOS]

### ISSUE THREAD

**Issue by mattrossman** [abhilash26/emotion-reader#2]
When trying the demo in Firefox (in Glitch or locally) this app throws the following error:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/22670878/84717915-51e83c80-af45-11ea-80b5-86d1c6185e05.png">

Unfortunately this trace points to the minimified Jeeliz library which makes it hard to see exactly what is causing the issue. I do know that weboji works in Firefox so it's not inherent to Jeeliz.

**Comment by abhilash26** [comment]
![Screenshot from 2020-06-17 10-12-57](https://user-images.githubusercontent.com/28080925/84856092-53b81a00-b083-11ea-8fcf-d32ea0af300b.png)

It works fine for me. 
I am using 77.0.1 (64-bit) version of Firefox on Ubuntu.

Thanks and Regards
Abhilash

**Comment by abhilash26** [comment]
Please post your firefox version as well as OS so I can test the issue.

**Comment by mattrossman** [comment]
I'm on Firefox 77.0.1 on MacOS. I just tested it on my Windows PC and it worked. It's weird that the issue is only affecting the MacOS version 🤔 

I will update the issue title to reflect this.

**Comment by abhilash26** [comment]
Thank you for quick reply and for changing the title .

I am really sorry. I don't own a mac OS now and probably not in near future, so I can't test the issue. Therefore, I will need help from others on this matter.

Just take the main library file of Jeeliz and I will tell which changes I have made in their file (if any). 
This should help in testing my changes to their file. Apart from that I have only added code.

Thanks and Regards,
Abhilash

**Comment by mattrossman** [comment]
No worries, I understand. I have been working with a different face library anyways so it's probably not worth the effort to debug it. I will close the issue for now, and if it's important to someone else they can reopen it and try to fix it.
